apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reactapp
  name: reactapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reactapp
    spec:
      containers:
      - image: stoneherc/react-app-image
        name: reactapp
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: reactapp
