apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  strategy: {}
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - image: stoneherc/node-chat-app:e5d7f720b543c336457c1c7fff60ef4e901ba834
          name: node-app
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: node-app
